### PR TITLE
Laravel 5.1 Shift

### PR DESCRIPTION
**Pull request by jasonmccreary**
This pull request includes the changes for upgrading to Laravel 5.1. Feel free to commit any additional changes to the `laravel-5.1-shift` branch.

**Before merging**, you should:

- Checkout the `laravel-5.1-shift` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the pre-commands fail, add `--no-scripts`)
- Thoroughly test your application

If you would like more help with your upgrade, check out the new [human services from Laravel Shift](https://laravelshift.com/human-services).

### CODE REVIEW

**Comment by jasonmccreary** [comment]
ℹ Laravel 5.1 changed the value of `$redirectTo` from `/home` to `/` in `app/Http/Controllers/Auth/AuthController.php`. I did not make this change since you may have customized it for your app. However, you may wish to change this if you are not using *Auth* or if you want to follow the latest Laravel conventions.

**Comment by jasonmccreary** [comment]
❌ I was unable to update `phpunit.xml` since yours differed from the Laravel default. You need to compare your `phpunit.xml` with the [Laravel 5.1 version](https://github.com/laravel-shift/laravel-5.1/blob/master/phpunit.xml) and merge any changes.

**Comment by jasonmccreary** [comment]
⚠ Laravel 5.1 changed some of the Node package dependencies. I could not reliably update `package.json` since yours differed from the Laravel default. You should to compare your `package.json` with the [Laravel 5.1 version](https://github.com/laravel-shift/laravel-5.1/blob/master/package.json) and update accordingly.

**Comment by jasonmccreary** [comment]
❌ I could not upgrade the following configuration files since they differed from the 5.1 defaults. You need to compare these configuration files against the [default Laravel 5.1 configuration files](https://github.com/laravel-shift/laravel-5.1/tree/master/config) and merge any changes:

- [ ] config/database.php
- [ ] config/mail.php

**Comment by jasonmccreary** [comment]
❌ Laravel 5.1 requires PHP 5.5.9+. You have an existing requirement for PHP in your `composer.json`. Ensure the version is `>=5.5.9`.

**Comment by jasonmccreary** [comment]
@davidweiner-df I'm at a good stopping point to get some of your feedback.

1. A few of the packages do not have Laravel 5 compatible versions. Reference *Remove* commits. I didn't see any references in the code to the *Captcha* package, but you may have references to the `Html5Inputs`. Let me know how you'd like to proceed...
2. It seems you had a pseudo custom namespace of `Medusa` located in the `App\Libraries` folders. There are not many classes in here, so I can run the *Consildate Namespaces Shift* to roll these back into the native L5 `App` namespace. Let me know if this is ok...

I still have about an hour left and provided your answers don't increase complexity, I should be able to complete *shifting* the project to 5.3 by tomorrow evening. You'll need to work through some bugs as I run it on your side, but they should be trivial.

**Comment by dweinerATL** [comment]
I replaced iorme/simplecaptcha with google/recaptcha, so ok to remove that.

smalldogs/html5inputs was added so I could use the html5 date input type with the Form helper.  If the laravelcollective/html Form helper has the html 5 date input type, then we're good.

If rolling the name space on those items in App\Libraries into the App namespace makes it easier, then go for it.

**Comment by jasonmccreary** [comment]
I'm not sure about the collective package managing HTML5 date inputs. Can
you check on this real quick to save me some time?

**Comment by dweinerATL** [comment]
Sure, I'm on it

**Comment by dweinerATL** [comment]
It does, we're good.

**Pull request merged**
