### PR TITLE
Laravel 5.0 Shift

### PR DESCRIPTION
**Pull request by dweinerATL**
This pull request includes the changes for upgrading to Laravel 5.0. Feel free to commit any additional changes to the `laravel-5.0-shift` branch.

**Before merging**, you should:

- Checkout the `laravel-5.0-shift` branch
- [Configure your environment](https://laravel.com/docs/5.0/upgrade#upgrade-5.0) for Laravel 5
- Update your dependencies for Laravel 5
- Review **all** pull request comments for additional changes
- Run `composer update` (if the pre-commands fail, add `--no-scripts`)
- Thoroughly test your application

If you would like more help with your upgrade, check out the new [human services from Laravel Shift](https://laravelshift.com/human-services).

### CODE REVIEW

**Comment by dweinerATL** [comment]
⚠ Laravel 5 only has model files in the top-level of the `app` folder. Your Laravel 4.2 app contained the following files within the `app` folder. You should move these files into another folder.

- [ ] app/events.php

**Comment by dweinerATL** [comment]
ℹ The new storage folders required by Laravel 5 have been merged with your existing `app/storage` folder. If you are not using custom storage paths in your app, you only need the `storage/app`, `storage/framework`, and `storage/logs` folders. You can remove the others.

**Comment by dweinerATL** [comment]
ℹ Laravel 5 offers [Elixir](http://laravel.com/docs/5.0/elixir) for asset management. Since Laravel 4.2 did not use Elixir, I did not configure your project to use it. If you wish to use Elixir, you should review the documentation and add the necessary files from a new Laravel 5 app.

**Comment by dweinerATL** [comment]
⚠ Your `app/filters.php` differs from the Laravel default. Laravel 5 now uses [Middleware](http://laravel.com/docs/5.0/middleware). Although you can still use *filters*, they will be removed in Laravel 5.2. I recommend you review `app/filters.php` and convert any custom filters to middleware.

**Comment by dweinerATL** [comment]
⚠ Laravel 5 enables CSRF protection by default. Since this was not enabled in Laravel 4.2, I disabled it. You should add [CSRF protection](http://laravel.com/docs/5.0/routing#csrf-protection) to your app then re-add `'App\Http\Middleware\VerifyCsrfToken'` to `$middleware` in `app/Http/Kernel.php`.

**Comment by dweinerATL** [comment]
❌ Your project still contains [Start Files](http://laravel.com/docs/4.2/lifecycle#start-files). Laravel 5 no longer uses these files. Review the files within `.unshifted-4.2-files/start` and migrate their contents to their respective Laravel 5 locations.

**Comment by dweinerATL** [comment]
❌ I could not upgrade the following configuration files since they differed from the 4.2 defaults. You need to compare these configuration files against the [default Laravel 5 configuration files](https://github.com/laravel-shift/laravel-5.0/tree/master/config) and merge any changes:

- [ ] auth.php
- [ ] cache.php
- [ ] compile.php
- [ ] database.php
- [ ] mail.php
- [ ] queue.php
- [ ] services.php
- [ ] session.php
- [ ] view.php

**Comment by dweinerATL** [comment]
❌ Laravel 5 does environment configuration differently. You need to copy `.env.example` to `.env`. This is the equivalent of the old `.env.php` file. Migrate any custom values you had in your old `.env.php` to the new `.env` file as well as any configuration values that vary by environment. You access these configuration values using the new `env()` method. Review the documentation on [Environment Configuration](http://laravel.com/docs/5.0/configuration#environment-configuration) for more details.

**Comment by dweinerATL** [comment]
❌ There are some legacy files within `.unshifted-4.2-files` you need to review.

**Comment by jasonmccreary** [comment]
Closing to rerun.

**Pull request closed without merging**
