### PR TITLE
Laravel 5.3 Shift

### PR DESCRIPTION
**Pull request by jasonmccreary**
This pull request includes the changes for upgrading to Laravel 5.3. Feel free to commit any additional changes to the `laravel-5.3-shift` branch.

**Before merging**, you should:

- Checkout the `laravel-5.3-shift` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the pre-commands fail, add `--no-scripts`)
- Thoroughly test your application

If you would like more help with your upgrade, check out the new [human services from Laravel Shift](https://laravelshift.com/human-services).

### CODE REVIEW

**Comment by jasonmccreary** [comment]
ℹ Laravel 5.3 no longer includes the `app/Events` folder by default. It is created for you when you make your first *Event* using `artisan`. I did not remove yours as it appears to differ from the default. However, if your app does not use *Events*, you can remove this folder manually to keep your app streamlined.

**Comment by jasonmccreary** [comment]
❌ Laravel 5.3 split the `Auth/AuthController.php` into the `Auth/LoginController.php` and the `Auth/RegisterController.php`. Since yours appears to be customized, I did not remove it. You should compare your `Auth/AuthController.php` with the newly added controllers and merge your changes accordingly.

**Comment by jasonmccreary** [comment]
❌ Laravel 5.3 renamed the `Auth/PasswordController.php` to `Auth/ResetPasswordController.php`. Since yours appears to be customized, I did not remove it. You should compare your `Auth/PasswordController.php` against the added `Auth/ResetPasswordController.php` and merge your changes accordingly.

**Comment by jasonmccreary** [comment]
⚠ If you are using *Authentication*, you should upgrade any routes using `AuthController` and `PasswordController` to use the new authentication controllers. Laravel recommends using the `Auth::routes()` which registers the proper routes for the new authentication controllers. This method also registers a `POST` route for `/logout` instead of a `GET` route.

**Comment by jasonmccreary** [comment]
❌ I was not able to update your `app/Providers/EventServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/EventServiceProvider.php) and merge the new changes.

**Comment by jasonmccreary** [comment]
ℹ Laravel 5.3 changed the redirect URL for an authenticated user from `/` to `/home` in `app/Http/Middleware/RedirectIfAuthenticated.php`. You may wish to change this depending on your app configuration. Otherwise, it may cause an infinite redirection loop.

**Comment by jasonmccreary** [comment]
⚠ Laravel 5.3 now includes a top-level `routes` folder. In addition, it separates routes into *API*, *console*, and *web* files.I have included a default `routes/api.php` and `routes/console.php` as well as migrated your `app/Http/routes.php` to `routes/web.php`. You should review your routes to see if they should be separated into one of the new route files.

**Comment by jasonmccreary** [comment]
⚠ The default behavior of `Route::resource()` changed in Laravel 5.3. All resource route parameters are now singularized by default and URL prefixes no longer affect the route names.You should review your resource routes and verify this singularized naming will not affect your parameters (or if you were doing this manually, you can remove the `parameter`). In addition, verify you are no longer appending the URI prefix to the route name.

Found `Route::resource()` in:

- [ ] routes/web.php

**Comment by jasonmccreary** [comment]
❌ I could not upgrade the following configuration files since they differed from the 5.2 defaults. You need to compare these configuration files against the [Laravel 5.3 configuration files](https://github.com/laravel-shift/laravel-5.3/blob/master/config) and merge any changes:

- [ ] config/auth.php
- [ ] config/cache.php
- [ ] config/database.php
- [ ] config/services.php
- [ ] config/session.php

**Comment by jasonmccreary** [comment]
❌ I could not upgrade the following project files since they differed from the 5.2 defaults. You need to compare these project files against the [default Laravel 5.3 versions](https://github.com/laravel-shift/laravel-5.3/) and merge any changes:

- [ ] gulpfile.js
- [ ] package.json

**Comment by jasonmccreary** [comment]
❌ Implicit controller routes using `Route::controller` were deprecated in Laravel 5.2 and removed in Laravel 5.3. Instead you should register your routes explicitly. You may be able to automate the conversion with an [artisan command](https://github.com/themsaid/laravel-routes-publisher).

Found `Route::controller()` in:

- [ ] routes/web.php

**Comment by jasonmccreary** [comment]
❌ Laravel 5.3 requires PHP 5.6.4+. You have an existing dependency for PHP in your `composer.json`. Ensure it meets the new version requirement of `>=5.6.4`.

**Comment by jasonmccreary** [comment]
❌ Laravel 5.3 has a development dependency for `symfony/css-selector` of `3.1.*`. You have a modified dependency for `symfony/css-selector` in your `composer.json`. Ensure it meets the new version requirement of `3.1.*`.

**Comment by jasonmccreary** [comment]
❌ Laravel 5.3 has a development dependency for `symfony/dom-crawler` of `3.1.*`. You have a modified dependency for `symfony/dom-crawler` in your `composer.json`. Ensure it meets the new version requirement of `3.1.*`.

**Comment by jasonmccreary** [comment]
❌ Laravel 5.3 `where` performs a "loose" comparison. In addition, the *strict* parameter was removed. If you need to perform a "strict" comparison, you can use `whereStrict` instead.

You should review the following usages of `where` to ensure you do not require "strict" compaison:

- [ ] app/Award.php
- [ ] app/Chapter.php
- [ ] app/Console/Commands/CodeTest.php
- [ ] app/Console/Commands/CreateEchelons.php
- [ ] app/Console/Commands/ImportGrades.php
- [ ] app/Console/Commands/AddPermission.php
- [ ] app/Console/Commands/ImportChapters.php
- [ ] app/Console/Commands/ChangePassword.php
- [ ] app/Console/Commands/DelPermission.php
- [ ] app/Console/Commands/MemberExport.php
- [ ] app/Console/Commands/ImportUsers.php
- [ ] app/Console/Commands/assignAHPerms.php
- [ ] app/Console/Commands/AddFleetCoPermission.php
- [ ] app/User.php
- [ ] app/Services/OAuthService.php
- [ ] app/Validators/MedusaValidators.php
- [ ] app/Billet.php
- [ ] app/Echelons/MedusaEchelons.php
- [ ] app/Http/Controllers/UnitController.php
- [ ] app/Http/Controllers/EchelonController.php
- [ ] app/Http/Controllers/BilletController.php
- [ ] app/Http/Controllers/UserController.php
- [ ] app/Http/Controllers/ReportController.php
- [ ] app/Http/Controllers/EventController.php
- [ ] app/Http/Controllers/ChapterController.php
- [ ] app/Http/Controllers/UserChangeRequestController.php
- [ ] app/Http/Controllers/ExamController.php
- [ ] app/Http/Controllers/ApiController.php
- [ ] app/Http/Controllers/TypeController.php
- [ ] app/MedusaConfig.php
- [ ] database/migrations/2015_09_27_205705_fix_empty_assignments.php
- [ ] database/migrations/2015_10_01_110734_create_rmmc_chapters.php
- [ ] database/migrations/2015_09_27_145914_update_scott_akers_reg_date.php
- [ ] database/migrations/2015_09_22_103459_set_assignment_dates.php
- [ ] database/migrations/2015_09_30_074311_create_rmmc_echelon_types.php
- [ ] database/migrations/2016_10_17_172330_add_chapter_show_config.php
- [ ] database/migrations/2015_10_01_181539_add_office_of_ha.php
- [ ] database/migrations/2016_01_22_194634_update_rank_titles.php
- [ ] database/migrations/2016_11_19_134132_new_chapter_types.php
- [ ] database/migrations/2016_01_17_222034_add_rank_equiv_info.php
- [ ] database/migrations/2016_10_09_185650_exam_regex.php
- [ ] database/migrations/2015_11_04_100140_add_SMCPON.php
- [ ] database/migrations/2016_01_17_221828_add_new_branches.php
- [ ] database/migrations/2016_11_15_143241_aerospacewings.php
- [ ] database/migrations/2015_09_17_140515_make_echelons_unjoinable.php
- [ ] database/migrations/2015_11_04_101458_update_Martin.php

**Comment by jasonmccreary** [comment]
❌ In Laravel 5.3, Eloquent scopes now respect the leading boolean of scope constraints. If you are starting your scope with an `orWhere` constraint it will no longer be converted to a normal `where`.

You should review the following usages of `orWhere` to ensure you're not starting your constraints with it:

- [ ] app/User.php
- [ ] app/Http/Controllers/ChapterController.php
- [ ] app/Http/Controllers/ApiController.php
- [ ] database/migrations/2016_11_19_134132_new_chapter_types.php

**Comment by jasonmccreary** [comment]
❌ The Query Builder returns collections, instead of plain arrays, in Laravel 5.3. You will need to upgrade your code to use collections or chain the `all()` method onto your query to return a plain array.

You should review the following usages of Query Builder:

- [ ] app/Http/Controllers/UserController.php
- [ ] database/seeds/TigSeeder.php
- [ ] database/seeds/BilletSeeder.php
- [ ] database/seeds/ChapterSeeder.php
- [ ] database/seeds/CountriesSeeder.php
- [ ] database/seeds/StatusSeeder.php
- [ ] database/seeds/TypeSeeder.php
- [ ] database/seeds/PermissionSeeder.php
- [ ] database/seeds/AuditSeeder.php
- [ ] database/seeds/RegStatusSeeder.php
- [ ] database/seeds/BranchSeeder.php
- [ ] database/seeds/UserSeeder.php
- [ ] database/seeds/GradeSeeder.php
- [ ] database/seeds/RatingSeeder.php
- [ ] database/migrations/2016_03_07_215817_knight_orders.php

**Comment by jasonmccreary** [comment]
ℹ If you are using *Queues*, you no longer need to specify the `--daemon` option when calling the `queue:work`. This is assumed in Laravel 5.3. Use the `--once` option to process a single job.

**Comment by jasonmccreary** [comment]
ℹ If you are using the `database` driver for your *Queue*, you will need to update your `jobs` and `failed_jobs` table. Review the *Queue* section of the [Laravel 5.3 Upgrade Guide](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0) for more details and feel free to use the [migrations from Laravel Shift](https://github.com/laravel-shift/laravel-5.3/tree/master/database/migrations).

**Comment by jasonmccreary** [comment]
ℹ Laravel 5.3 updated several of the default assets as well as adding support for [Vue.js](https://vuejs.org). If you are using Laravel to [compile assets](https://laravel.com/docs/5.3/elixir) you may want to review the latest versions of [`resources/assets/js/app.js`](https://github.com/laravel-shift/laravel-5.3/blob/master/resources/assets/js/app.js) and [`resources/assets/sass/app.scss`](https://github.com/laravel-shift/laravel-5.3/blob/master/resources/assets/sass/app.scss) and update your project accordingly.

**Comment by jasonmccreary** [comment]
⚠ Laravel 5.3 added configuration for your application name in `config/app.php`. Be sure to set this value as it is used in notifications, like the password reset email.

**Comment by jasonmccreary** [comment]
ℹ If you have manually upgraded your app for previous versions of Laravel, I recommend running the [Laravel Linter](https://laravelshift.com/laravel-linter) to ensure your app is fully upgraded to the latest version of Laravel.

**Comment by jasonmccreary** [comment]
@davidweiner-df I'm getting close to time and like to save the last bit for *handoff*. Here's what's left in order of priority:

1. Review the 👎 and comments with incomplete tasks above that are related to *routes*.
2. Smoke test the latest dependencies. If you can get `php artisan` to run without chocking, it's a good start.
3. Ensure you can connect to MongoDB. Depending on your version, you may need to [adjust your configuration](https://github.com/jenssegers/laravel-mongodb#configuration).
4. Verify the app runs by adjusting your environment configuration. I have created `.env.prod` and `.env.local` as starting points.
5. Review any remaining 👎 items above.
6. I did not update any of your npm/gulp setup as it appeared custom. So you may want to review this more closely.

If you would like to purchase another 3-hour block, I can continue with items 1, 2, 5, 6 and have time left to start on Passport. However, at some point you will still need to work through items 3, 4. So feel free to *smoke test* now and let me know.

**Comment by dweinerATL** [comment]
I will try to review things, but I may not be able to do much until after I get back from the cruise on the 19th.  If I can work through them and get the app running, I may take a stab at Passport, since under the hood, I'm using the league oauth server already :)

**Comment by dweinerATL** [comment]
When I tried to run composer update, I got 'PHP Fatal error:  Class 'App\Libraries\MedusaHasherServiceProvider' not found in ProviderRepository.php on line 146

Looking at the ProviderRepository.php, it looked like a pathing/auto-loader issue, so I comment it out, run composer update and again, and I get "Class hash does not exist".

I ended up moving MedusaHasherServiceProvider into the app/Services directory and changing the namespace.  After that and a few updates to packages, I was able to get composer update to run.

Once I commented out the references to the password reminder controller in the login form, I was able to get the login form to come up, but it just hangs with nothing in the log files when I try and log in.  I'll take a stab at the auth stuff next, and work my way through things.

How much time is left of the first 3 hour block?

**Comment by jasonmccreary** [comment]
@davidweiner-df awesome.

I have about 15 minutes left. Unfortunately, without having MongoDB setup locally it's unlikely I will be able to debug the issue in that time.

My suggestion would be to use the last bit of time for a coaching session. If those prove to resolve the issue, you are welcome to purchase more for us to work on the OAuth to Passport transition. I'll offer 20% off.

**Comment by dweinerATL** [comment]
Sounds good @jasonmccreary.  I expect that I need to work on the Authentication bits next to get the login working, and yes, I was thinking exactly the same thing, use whatever time is left for a coaching session.  I don't think I'm going to be able to get anything else done before  I leave on the cruise, so I will be in touch when I get back to make the arrangements for the coaching session.

**Comment by jasonmccreary** [comment]
Sounds good. My guess is the authentication changed so much between 4.2 and 5.0. Since you are using MongoDB, you might need to write and register a [custom guard](https://laravel.com/docs/5.3/authentication#adding-custom-guards). I imagine some exist with some Google magic.

Just let me know about the coaching session. Not sure your time zone, but I can do 15 minutes this evening or over lunch tomorrow (Eastern Time).

**Comment by dweinerATL** [comment]
I am in the Eastern time zone as well, but I am having people over tonight, I'm packing tomorrow and leaving on Thursday.  Plus, I'm going to want to review the auth and mongo stuff before hand, and maybe even make an attempt and updating it before we do the coaching session :)

**Comment by jasonmccreary** [comment]
No problem. Enjoy the cruise. Email me whenever you're ready.

**Comment by dweinerATL** [comment]
You got it!

**Comment by dweinerATL** [comment]
JMac,

I've gotten authentication working with Mongo, which is good.  I'm working through things, and it looks like in L5.3, the parameter order for the array_where() helper function switched from $key, $value to $value, $key!!!  Do you know if this was intentional?  I mean, that's a breaking change and shouldn't be in a dot release.  If that was intended, I'm going to have to overload array_where to switch them back, as I use that helper quite a lot in the code!

Dave

**Comment by jasonmccreary** [comment]
Great!

Yes, it was an intentional change. Several of these collection and helper methods changed. While I agree, Laravel does not follow semantic versioning.

I would not suggest overloading it. While it might take a bit, it's a straightforward change and you might be able to get away with a fancy find and replace.

**Comment by dweinerATL** [comment]
I'm shocked that Laravel does not follow semantic versioning and would introduce so many breaking changes in a dot release.

Thanks for the input.....

**Comment by dweinerATL** [comment]
Next question -- In a number of my views, I call models directly, such as User::where('foo', '=', 'bar')->first()

With the new namespacing, they're not being found unless I change them to \App\Model -- is there any way to avoid this?

**Comment by jasonmccreary** [comment]
No unless you import the namespace with a `use` statement.

I'd recommend:

- Referencing it with the full namespace
- Not hitting your models directly from views, but instead use the controller. [Views should be dumb](http://softwareengineering.stackexchange.com/a/271639).

**Comment by dweinerATL** [comment]
Look for an incoming email about the coaching @jasonmccreary

**Comment by dweinerATL** [comment]
Never mind @jasonmccreary !  As I was typing the email, explaining things, I figured it out :)

**Comment by jasonmccreary** [comment]
Rubber ducking works :smh

**Pull request merged**
